name: Docker Image CI

on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io

jobs:

  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    - name: Build and publish docker into registry
      uses: VaultVulp/gp-docker-action@1.0.1
      with:
        submodules: 'recursive'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: triplifier-boot
        image-tag: latest
